spring.datasource.url=jdbc:postgresql://dpg-d794cpkhg0os73e1oedg-a.oregon-postgres.render.com:5432/interviewdb_wzjv
spring.datasource.username=interviewuser
spring.datasource.password=M65u4eMnmqsR2KXTncvlIo1akiEnHN3i

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8080}
groq.api.key=${GROQ_API_KEY}